// EMIT_MIR small_blocks_inliner_threshold_flipped_condition.main.Inline.after.mir

// Test case generated to detect flipped threshold condition on `check_mir_body`.
// The decision of whether to inline (or not) a block of code is decided by its 
// cost of inlining, compared to the block's inline threshold
// Normally small bonus is given to the inline threshold for small blocks, via
//  threshold += threshold / 4
// where inline will only be performed if the cost <= threshold.

// This test checks that the decision to increase the threshold for small blocks
// has been applied correctly. This test was generated by a fuzzer.

use std::collections::hash_map::DefaultHasher;
use std::hash::Hash;

fn main() {
  let mut a = DefaultHasher::new ();
  let b = &mut a;
  "".hash(b)
}